#!/usr/bin/env python3
"""
Annotation Tool — Flask web application.

Two tasks:
  Task 1  /task1/<idx>  — Annotate user attributes (per user)
  Task 2  /task2/<idx>  — Annotate checklist relevance (per user-prompt pair)

Run:
    python3 app.py [--port 5050]
"""

from __future__ import annotations

import argparse
import html
import json
import os
import random
import time
from collections import Counter
from datetime import datetime
from itertools import combinations
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from flask import (
    Flask,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

# ─── Paths ────────────────────────────────────────────────────────────────────
BASE_DIR    = Path(__file__).parent
ANNOT_DIR   = BASE_DIR / "data" / "annotations"
ANNOT_DIR.mkdir(parents=True, exist_ok=True)

# Generated by: python3 build_index.py [--extract-only]
TASK1_ITEMS = BASE_DIR / "data" / "extracted" / "task1_items.jsonl"
TASK2_ITEMS = BASE_DIR / "data" / "extracted" / "task2_items.jsonl"
TASK4_ITEMS = BASE_DIR / "data" / "extracted" / "task4_items.jsonl"
TASK5_ITEMS = BASE_DIR / "data" / "extracted" / "task5_items.jsonl"
TASK6_ITEMS = BASE_DIR / "data" / "extracted" / "task6_items.jsonl"

# ─── Task settings (overridable via CLI) ──────────────────────────────────────
TASK1_MAX_USERS   = 100  # Only show the first N users for Task 1
TASK2_MAX_ITEMS   = 0    # 0 = no limit; set via --task2-max-items
TASK3_MAX_PROMPTS = 5    # Max unique prompts for Task 3; set via --task3-max-prompts
TASK4_START       = 0    # First item index shown for Task 4 (inclusive)
TASK4_END         = 0    # Last item index shown for Task 4 (exclusive; 0 = no limit)
TASK5_MAX_PROMPTS = 100    # Max unique prompts for Task 5; set via --task5-max-prompts
TASK6_MAX_ITEMS   = 0    # 0 = no limit; set via --task6-max-items

# ─── Flask setup ──────────────────────────────────────────────────────────────
app = Flask(__name__)
app.secret_key = "annotation-tool-secret-2024"


@app.context_processor
def inject_annotator():
    return {"current_annotator": annotator_name()}

# ─── Data (loaded once at startup from JSONL files) ───────────────────────────
# Generate these files with: python3 build_index.py [--extract-only]
# Hand-crafted records can also be appended directly to task1_items.jsonl.

_task1_items: List[Dict] = []  # one entry per user (attrs + embedded conversations)
_task2_items: List[Dict] = []  # one entry per checklist item (used by Task 2 & 3)
_task4_items: List[Dict] = []  # round-2 version of task1 items
_task5_items: List[Dict] = []  # round-2 version of task2 items (drives task5 prompts)
_task6_items: List[Dict] = []  # one item per (user, prompt) pair with both responses


def _load_data() -> None:
    global _task1_items, _task2_items, _task4_items, _task5_items, _task6_items
    if TASK1_ITEMS.exists():
        with open(TASK1_ITEMS, "r", encoding="utf-8") as f:
            _task1_items = [json.loads(ln) for ln in f if ln.strip()]
        _task1_items.sort(key=lambda r: r.get("item_index", 0))
        print(f"Loaded {len(_task1_items)} task1 items.", flush=True)
    else:
        print(f"Warning: {TASK1_ITEMS} not found. Run: python3 build_index.py", flush=True)

    if TASK2_ITEMS.exists():
        with open(TASK2_ITEMS, "r", encoding="utf-8") as f:
            _task2_items = [json.loads(ln) for ln in f if ln.strip()]
        _task2_items.sort(key=lambda r: r.get("item_index", 0))
        print(f"Loaded {len(_task2_items)} task2 items.", flush=True)
    else:
        print(f"Warning: {TASK2_ITEMS} not found. Run: python3 build_index.py", flush=True)

    if TASK4_ITEMS.exists():
        with open(TASK4_ITEMS, "r", encoding="utf-8") as f:
            _task4_items = [json.loads(ln) for ln in f if ln.strip()]
        _task4_items.sort(key=lambda r: r.get("item_index", 0))
        print(f"Loaded {len(_task4_items)} task4 items.", flush=True)
    else:
        print(f"Warning: {TASK4_ITEMS} not found.", flush=True)

    if TASK5_ITEMS.exists():
        with open(TASK5_ITEMS, "r", encoding="utf-8") as f:
            _task5_items = [json.loads(ln) for ln in f if ln.strip()]
        _task5_items.sort(key=lambda r: r.get("item_index", 0))
        print(f"Loaded {len(_task5_items)} task5 items.", flush=True)
    else:
        print(f"Warning: {TASK5_ITEMS} not found.", flush=True)

    if TASK6_ITEMS.exists():
        with open(TASK6_ITEMS, "r", encoding="utf-8") as f:
            _task6_items = [json.loads(ln) for ln in f if ln.strip()]
        _task6_items.sort(key=lambda r: r.get("item_index", 0))
        print(f"Loaded {len(_task6_items)} task6 items.", flush=True)
    else:
        print(f"Warning: {TASK6_ITEMS} not found.", flush=True)


_load_data()

# ─── Attribute evidence cache ──────────────────────────────────────────────────
# Loaded from data/attr_evidence_cache.jsonl, produced by generate_attr_evidence.py
# Maps "source:user_id" -> list of evidence dicts (one per attribute).
ATTR_EVIDENCE_FILE = BASE_DIR / "data" / "attr_evidence_cache.jsonl"
_attr_evidence: Dict[str, List] = {}


def _load_attr_evidence() -> None:
    global _attr_evidence
    if not ATTR_EVIDENCE_FILE.exists():
        return
    with open(ATTR_EVIDENCE_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
                key = rec.get("cache_key")
                ev = rec.get("evidence", [])
                if key:
                    _attr_evidence[key] = ev
            except Exception:
                continue
    print(f"Loaded attr evidence for {len(_attr_evidence)} users.", flush=True)


_load_attr_evidence()


# ─── Expected behaviors cache ─────────────────────────────────────────────────
# Loaded from data/behaviors/*.jsonl, produced by generate_expected_behaviors.py.
# _behaviors[sample_index][attribute_text] = {model: {"explicit": "...", "implicit": "..."}}
BEHAVIORS_DIR = BASE_DIR / "data" / "behaviors"
_behaviors: Dict[int, Dict[str, Dict[str, Dict[str, str]]]] = {}


def _load_behaviors() -> None:
    global _behaviors
    if not BEHAVIORS_DIR.exists():
        return
    files = sorted(BEHAVIORS_DIR.glob("*.jsonl"))
    if not files:
        return
    loaded_models: List[str] = []
    for fpath in files:
        with open(fpath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                    sidx = rec.get("sample_index")
                    model = rec.get("model", fpath.stem)
                    if sidx is None:
                        continue
                    _behaviors.setdefault(sidx, {})
                    for item in rec.get("items", []):
                        attr = item.get("attribute", "")
                        if not attr:
                            continue
                        _behaviors[sidx].setdefault(attr, {})[model] = {
                            "explicit": item.get("explicit_behavior", ""),
                            "implicit": item.get("implicit_behavior", ""),
                        }
                except Exception:
                    continue
        loaded_models.append(fpath.name)
    print(
        f"Loaded expected behaviors for {len(_behaviors)} samples "
        f"from {len(loaded_models)} file(s): {', '.join(loaded_models)}",
        flush=True,
    )


_load_behaviors()


# ─── Relevance classifications from LLMs ──────────────────────────────────────
# Loaded from data/relevance_task{3,5}/*.jsonl, produced by classify_attribute_relevance.py.
# _relevance_task3/5[sample_index][attribute_text][model] = True/False
RELEVANCE_DIR_TASK3 = BASE_DIR / "data" / "relevance_task3"
RELEVANCE_DIR_TASK5 = BASE_DIR / "data" / "relevance_task5"
_relevance_task3: Dict[int, Dict[str, Dict[str, bool]]] = {}
_relevance_task5: Dict[int, Dict[str, Dict[str, bool]]] = {}


def _load_relevance_from(relevance_dir: Path) -> Dict[int, Dict[str, Dict[str, bool]]]:
    result: Dict[int, Dict[str, Dict[str, bool]]] = {}
    if not relevance_dir.exists():
        return result
    files = sorted(relevance_dir.glob("*.jsonl"))
    loaded_models: List[str] = []
    for fpath in files:
        with open(fpath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                    sidx = rec.get("sample_index")
                    model = rec.get("model", fpath.stem)
                    if sidx is None:
                        continue
                    result.setdefault(sidx, {})
                    for item in rec.get("items", []):
                        attr = item.get("attribute", "")
                        if not attr:
                            continue
                        result[sidx].setdefault(attr, {})[model] = bool(item.get("relevant", False))
                except Exception:
                    continue
        loaded_models.append(fpath.name)
    if loaded_models:
        print(
            f"Loaded relevance from {relevance_dir.name}: {len(result)} samples "
            f"from {len(loaded_models)} file(s): {', '.join(loaded_models)}",
            flush=True,
        )
    return result


def _load_relevance() -> None:
    global _relevance_task3, _relevance_task5
    _relevance_task3 = _load_relevance_from(RELEVANCE_DIR_TASK3)
    _relevance_task5 = _load_relevance_from(RELEVANCE_DIR_TASK5)


_load_relevance()


# ─── Task 3 prompt-level data ─────────────────────────────────────────────────
# Groups task2 records by prompt_index, merges all users' profile attributes
# for each prompt, and shuffles them with a deterministic seed (prompt_index) so
# every annotator sees the same randomized order.
#
# Each entry:  {prompt_index, prompt_text, attributes: [{attribute, user_id, sample_index}]}
# Stored in canonical shuffled order; judgments are saved by attribute text.
_task3_prompts: List[Dict] = []


def _build_task3_prompts() -> None:
    global _task3_prompts
    if not _task2_items:
        return
    groups: Dict[int, Dict] = {}
    for i, rec in enumerate(_task2_items):
        pidx = rec.get("prompt_index", -1)
        if pidx < 0:
            continue
        if pidx not in groups:
            groups[pidx] = {
                "prompt_index": pidx,
                "prompt_text":  rec.get("prompt_text", ""),
                "attributes":   [],
                "seen":         set(),
            }
        for attr in rec.get("profile_attributes", []):
            attr.pop("embedding", None)
            text = attr.get("attribute", "")
            if text and text not in groups[pidx]["seen"]:
                groups[pidx]["seen"].add(text)
                groups[pidx]["attributes"].append({
                    "attribute":    text,
                    "user_id":      rec.get("user_id", ""),
                    "sample_index": i,
                })

    _task3_prompts = []
    for pidx in sorted(groups.keys()):
        g = groups[pidx]
        attrs_orig = list(g["attributes"])          # original insertion order (for admin)
        attrs = list(attrs_orig)
        random.Random(pidx).shuffle(attrs)           # reproducible per-prompt shuffle (for annotators)
        _task3_prompts.append({
            "prompt_index":    pidx,
            "prompt_text":     g["prompt_text"],
            "attributes":      attrs,
            "attributes_orig": attrs_orig,
        })
    print(f"Built {len(_task3_prompts)} Task-3 prompts "
          f"(limit: {TASK3_MAX_PROMPTS}).", flush=True)


_build_task3_prompts()


# ─── Task 5 prompt-level data ─────────────────────────────────────────────────
# Same structure as _task3_prompts but built from _task5_items.

_task5_prompts: List[Dict] = []


def _build_task5_prompts() -> None:
    global _task5_prompts
    if not _task5_items:
        return
    groups: Dict[int, Dict] = {}
    for i, rec in enumerate(_task5_items):
        pidx = rec.get("prompt_index", -1)
        if pidx < 0:
            continue
        if pidx not in groups:
            groups[pidx] = {
                "prompt_index": pidx,
                "prompt_text":  rec.get("prompt_text", ""),
                "attributes":   [],
                "seen":         set(),
            }
        for attr in rec.get("profile_attributes", []):
            attr.pop("embedding", None)
            text = attr.get("attribute", "")
            if text and text not in groups[pidx]["seen"]:
                groups[pidx]["seen"].add(text)
                groups[pidx]["attributes"].append({
                    "attribute":    text,
                    "user_id":      rec.get("user_id", ""),
                    "sample_index": i,
                })

    _task5_prompts = []
    for pidx in sorted(groups.keys()):
        g = groups[pidx]
        attrs_orig = list(g["attributes"])
        attrs = list(attrs_orig)
        random.Random(pidx).shuffle(attrs)
        _task5_prompts.append({
            "prompt_index":    pidx,
            "prompt_text":     g["prompt_text"],
            "attributes":      attrs,
            "attributes_orig": attrs_orig,
        })
    print(f"Built {len(_task5_prompts)} Task-5 prompts "
          f"(limit: {TASK5_MAX_PROMPTS}).", flush=True)


_build_task5_prompts()


# ─── Data helpers ─────────────────────────────────────────────────────────────

def attrs_count() -> int:
    return min(len(_task1_items), TASK1_MAX_USERS)


def checklist_count() -> int:
    n = len(_task2_items)
    return min(n, TASK2_MAX_ITEMS) if TASK2_MAX_ITEMS > 0 else n


def task3_count() -> int:
    n = len(_task3_prompts)
    return min(n, TASK3_MAX_PROMPTS) if TASK3_MAX_PROMPTS > 0 else n


def attrs4_count() -> int:
    """Number of task4 items visible in the current range."""
    n = len(_task4_items)
    end = TASK4_END if TASK4_END > 0 else n
    return max(0, min(end, n) - TASK4_START)


def task4_global_idx(local_idx: int) -> int:
    """Convert a 0-based local navigation index to the global annotation index."""
    return TASK4_START + local_idx


def task5_count() -> int:
    n = len(_task5_prompts)
    return min(n, TASK5_MAX_PROMPTS) if TASK5_MAX_PROMPTS > 0 else n


def task6_count() -> int:
    n = len(_task6_items)
    return min(n, TASK6_MAX_ITEMS) if TASK6_MAX_ITEMS > 0 else n


def fetch_attrs_record(idx: int) -> Optional[Dict]:
    if 0 <= idx < len(_task1_items):
        return _task1_items[idx]
    return None


def fetch_attrs4_record(local_idx: int) -> Optional[Dict]:
    """Fetch task4 record by local (0-based) index within the configured range."""
    global_idx = task4_global_idx(local_idx)
    if 0 <= global_idx < len(_task4_items):
        return _task4_items[global_idx]
    return None


def fetch_checklist_record(idx: int) -> Optional[Dict]:
    if 0 <= idx < len(_task2_items):
        return _task2_items[idx]
    return None


def get_checklist_meta_list() -> List[Dict]:
    return [
        {
            "annotation_index": i,
            "user_id": r.get("user_id", ""),
            "prompt_index": r.get("prompt_index", -1),
            "prompt_snippet": (r.get("prompt_text") or "")[:120],
        }
        for i, r in enumerate(_task2_items)
    ]


def get_attrs_meta_list() -> List[Dict]:
    return [
        {"line_index": i, "user_id": r.get("user_id", "")}
        for i, r in enumerate(_task1_items)
    ]


def get_attrs4_meta_list() -> List[Dict]:
    """Return meta entries for the configured task4 range; line_index is the global index."""
    n = len(_task4_items)
    end = TASK4_END if TASK4_END > 0 else n
    end = min(end, n)
    return [
        {"line_index": TASK4_START + local_i, "user_id": _task4_items[TASK4_START + local_i].get("user_id", "")}
        for local_i in range(max(0, end - TASK4_START))
    ]


# ─── Annotation helpers ───────────────────────────────────────────────────────

ADMIN_NAME = "admin"

def annotator_name() -> Optional[str]:
    return session.get("annotator_name")


def is_admin() -> bool:
    return annotator_name() == ADMIN_NAME


def load_all_annotators(task: str) -> Dict[str, Dict[str, Any]]:
    """Load annotations from every annotator file for a task (skips admin).
    Returns {annotator_safe_name: {index_str: record}}.
    """
    suffix = f"_task{task}.jsonl"
    result: Dict[str, Dict[str, Any]] = {}
    for fpath in sorted(ANNOT_DIR.glob(f"*{suffix}")):
        annotator = fpath.name[: -len(suffix)]
        if annotator == ADMIN_NAME:
            continue
        recs: Dict[str, Any] = {}
        with open(fpath, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                    key = str(rec.get("index", ""))
                    if key:
                        recs[key] = rec
                except Exception:
                    continue
        if recs:
            result[annotator] = recs
    return result


def _build_task1_global_stats(
    all_annots: Dict[str, Dict[str, Any]],
    items: List[Any],
) -> Dict:
    """Global stats for the task-1 admin summary panel."""
    CATS = ["ok", "unsure", "bad"]
    item_n_attrs = {item["item_index"]: len(item.get("merged_attributes", [])) for item in items}

    # Flatten per annotator: list of (item_idx, attr_idx, judgment)
    ann_judgments: Dict[str, List[Tuple[int, int, str]]] = {}
    for ann, recs in all_annots.items():
        triples: List[Tuple[int, int, str]] = []
        for idx_str, rec in recs.items():
            item_idx = int(idx_str)
            for a_idx, aj in enumerate(rec.get("attr_judgments", [])):
                j = aj.get("judgment")
                if j:
                    triples.append((item_idx, a_idx, j))
        if triples:
            ann_judgments[ann] = triples

    # Label rates per annotator
    label_rates = []
    for ann in sorted(ann_judgments):
        triples = ann_judgments[ann]
        n = len(triples)
        counts = Counter(j for _, _, j in triples)
        label_rates.append({
            "annotator": ann,
            "n": n,
            "ok_pct":     counts.get("ok", 0) / n,
            "unsure_pct": counts.get("unsure", 0) / n,
            "bad_pct":    counts.get("bad", 0) / n,
            "n_ok":     counts.get("ok", 0),
            "n_unsure": counts.get("unsure", 0),
            "n_bad":    counts.get("bad", 0),
        })

    # Pairwise % agreement + Cohen's κ
    pairwise = []
    for a1, a2 in combinations(sorted(ann_judgments.keys()), 2):
        d1 = {(i, a): j for i, a, j in ann_judgments[a1]}
        d2 = {(i, a): j for i, a, j in ann_judgments[a2]}
        shared = sorted(set(d1) & set(d2))
        if len(shared) < 2:
            continue
        j1 = [d1[k] for k in shared]
        j2 = [d2[k] for k in shared]
        n = len(j1)
        p_o = sum(a == b for a, b in zip(j1, j2)) / n
        p_e = sum((j1.count(c) / n) * (j2.count(c) / n) for c in CATS)
        kappa = (p_o - p_e) / (1 - p_e) if p_e < 1.0 else None
        pairwise.append({"ann_a": a1, "ann_b": a2, "agree_pct": p_o, "kappa": kappa, "n": n})

    pairwise.sort(key=lambda x: -x["n"])

    n_annotated = len({
        int(idx_str)
        for recs in all_annots.values()
        for idx_str in recs.keys()
    })

    return {
        "label_rates": label_rates,
        "pairwise": pairwise,
        "n_items_total": len(items),
        "n_items_annotated": n_annotated,
    }


def annot_file(task: str) -> Path:
    name = annotator_name() or "unknown"
    safe = "".join(c if c.isalnum() or c in "-_." else "_" for c in name)
    return ANNOT_DIR / f"{safe}_task{task}.jsonl"


def load_existing_annotations(task: str) -> Dict[str, Any]:
    """Load existing annotations into a dict keyed by record index string."""
    path = annot_file(task)
    result: Dict[str, Any] = {}
    if not path.exists():
        return result
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
                key = str(rec.get("index", ""))
                if key:
                    result[key] = rec
            except Exception:
                continue
    return result


import fcntl

def save_annotation(task: str, record: Dict) -> None:
    record["annotator"] = annotator_name()
    record["timestamp"] = datetime.utcnow().isoformat()

    path = annot_file(task)
    lock_path = path.with_suffix(".lock")
    
    with open(lock_path, "w") as lock_fh:
        fcntl.flock(lock_fh, fcntl.LOCK_EX)
        try:
            all_records = load_existing_annotations(task)
            all_records[str(record["index"])] = record
            tmp_path = path.with_suffix(".jsonl.tmp")
            with open(tmp_path, "w", encoding="utf-8") as f:
                for rec in all_records.values():
                    f.write(json.dumps(rec, ensure_ascii=False) + "\n")
            tmp_path.replace(path)
        finally:
            fcntl.flock(lock_fh, fcntl.LOCK_UN)


def count_annotated(task: str, total: int, offset: int = 0) -> int:
    """Count how many of the total items this annotator has fully completed.

    offset: for tasks that use a global index (e.g. task4 with a range), the
    annotation key is offset+i rather than i.
    """
    existing = load_existing_annotations(task)
    count = 0
    if task in ("3", "5"):
        prompts = _task3_prompts if task == "3" else _task5_prompts
        limit   = task3_count()  if task == "3" else task5_count()
        for prompt_rec in prompts[:limit]:
            attrs = prompt_rec.get("attributes", [])
            prompt_done = False
            for attr_entry in attrs:
                rec = existing.get(str(attr_entry["sample_index"]))
                if rec and rec.get("flagged"):
                    prompt_done = True
                    break
            if not prompt_done:
                prompt_done = bool(attrs) and all(
                    any(
                        j.get("attribute") == a["attribute"] and j.get("relevant") is not None
                        for j in existing.get(str(a["sample_index"]), {}).get("relevance_judgments", [])
                    )
                    for a in attrs
                )
            if prompt_done:
                count += 1
        return count
    for i in range(total):
        rec = existing.get(str(offset + i))
        if not rec:
            continue
        if rec.get("flagged"):
            count += 1
        elif task in ("1", "4"):
            judgments = rec.get("attr_judgments", [])
            if judgments and all(j.get("judgment") for j in judgments):
                count += 1
        elif task == "2":
            judgments = rec.get("relevance_judgments", [])
            if judgments and all(j.get("rating") not in (None, "none", "") for j in judgments):
                count += 1
        elif task == "6":
            item = _task6_items[i] if i < len(_task6_items) else None
            if item:
                n_attrs = len(item.get("items", []))
                judgments = rec.get("personalization_judgments", [])
                if n_attrs > 0 and len(judgments) == n_attrs and all(
                    j.get("better") is not None for j in judgments
                ):
                    count += 1
    return count


# ─── Conversation HTML builder (adapted from visualize_score_assistant_like_usage.py) ──

def build_chat_html(conversations: Any, max_convs: int = 500, max_turns_per_conv: int = 500,
                    short_chars: int = 200, long_chars: int = 10000,
                    c_idx_start: int = 0, total_panels: int = 1) -> str:
    if not conversations:
        return '<div class="chat-empty">No messages.</div>'

    convs = conversations
    if isinstance(convs, list) and convs and isinstance(convs[0], dict):
        # Single flat conversation — wrap it
        convs = [convs]

    # Show label when there are multiple sub-conversations within this record,
    # or when this record is one of several panels for the same user.
    show_label = len(convs) > 1 or total_panels > 1

    html_parts: List[str] = []
    turns_shown = 0
    truncated = False

    for c_idx, conv_turns in enumerate(convs or []):
        if c_idx >= max_convs:
            truncated = True
            break
        if show_label:
            html_parts.append(f'<div class="conv-label">Conversation {c_idx_start + c_idx + 1}</div>')

        turns_in_conv = 0
        for t_idx, turn in enumerate(conv_turns):
            if turns_in_conv >= max_turns_per_conv:
                html_parts.append('<div class="chat-more-hint">… more turns in this conversation not shown.</div>')
                break
            if not isinstance(turn, dict):
                continue
            role  = (turn.get("role") or "").upper()
            text  = (turn.get("content") or "").strip()
            if not text:
                continue

            role_class = "msg-user" if role == "USER" else (
                "msg-assistant" if role in {"ASSISTANT", "SYSTEM", "TOOL"} else "msg-other"
            )
            safe_role = html.escape(role)
            data_attrs = f'data-conv-idx="{c_idx_start + c_idx}" data-turn-idx="{t_idx}"'

            if len(text) <= short_chars:
                # Short enough — plain non-expandable div
                html_parts.append(
                    f'<div class="msg-details" {data_attrs}>'
                    f'<div class="msg {role_class}">'
                    f'<div class="msg-role">{safe_role}</div>'
                    f'<div class="msg-text">{html.escape(text)}</div>'
                    f'</div></div>'
                )
            else:
                hint = (
                    ' <span class="expand-hint">↕ click to expand</span>'
                )
                short_text = html.escape(text[:short_chars]) + hint
                long_text  = html.escape(text[:long_chars]) + (html.escape("…") if len(text) > long_chars else "")
                html_parts.append(
                    f'<details class="msg-details" {data_attrs}>'
                    f'<summary><div class="msg {role_class}">'
                    f'<div class="msg-role">{safe_role}</div>'
                    f'<div class="msg-text msg-short">{short_text}</div>'
                    f'<div class="msg-text msg-full">{long_text}</div>'
                    f'</div></summary>'
                    f'</details>'
                )
            turns_in_conv += 1
            turns_shown += 1

    if turns_shown == 0:
        return '<div class="chat-empty">No messages.</div>'
    if truncated:
        html_parts.append(f'<div class="chat-more-hint">Showing first {max_convs} of {len(convs)} conversations.</div>')
    return "".join(html_parts)


# ─── Routes: auth ─────────────────────────────────────────────────────────────

def _next_redirect(next_task: str):
    """Redirect to the task indicated by next_task, or the select page."""
    if next_task == "task1":
        return redirect(url_for("task1_view", idx=0))
    if next_task == "task2":
        return redirect(url_for("task2_view", idx=0))
    if next_task == "task3":
        return redirect(url_for("task3_view", idx=0))
    if next_task == "task4":
        return redirect(url_for("task4_view", idx=0))
    if next_task == "task5":
        return redirect(url_for("task5_view", idx=0))
    if next_task == "task6":
        return redirect(url_for("task6_view", idx=0))
    return redirect(url_for("task_select"))


@app.route("/", methods=["GET", "POST"])
def index():
    # Auto-login via Prolific PID passed in the study URL query string
    prolific_pid = request.args.get("PROLIFIC_PID", "").strip()
    next_task = request.args.get("next", "").strip()
    if prolific_pid:
        session["annotator_name"] = prolific_pid
        return _next_redirect(next_task)
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        next_task = request.form.get("next", "").strip()
        if name:
            session["annotator_name"] = name
            return _next_redirect(next_task)
    return render_template("login.html", current_name=annotator_name(), next_task=next_task)


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))


@app.route("/select")
def task_select():
    if not annotator_name():
        return redirect(url_for("index"))
    t1_count = attrs_count()
    t2_count = checklist_count()
    t1_ready = bool(_task1_items)
    t2_ready = bool(_task2_items)
    t4_count = attrs4_count()
    t5_count = task5_count()
    t6_count = task6_count()
    t4_ready = bool(_task4_items)
    t5_ready = bool(_task5_items)
    t6_ready = bool(_task6_items)
    return render_template(
        "select.html",
        annotator=annotator_name(),
        t1_count=t1_count,
        t2_count=t2_count,
        t1_ready=t1_ready,
        t2_ready=t2_ready,
        t4_count=t4_count,
        t4_start=TASK4_START,
        t4_end=TASK4_END,
        t5_count=t5_count,
        t6_count=t6_count,
        t4_ready=t4_ready,
        t5_ready=t5_ready,
        t6_ready=t6_ready,
    )


# ─── Routes: Task 1 — User Attribute Annotation ───────────────────────────────

@app.route("/task1")
def task1_redirect():
    if not annotator_name():
        return redirect(url_for("index", next="task1"))
    return redirect(url_for("task1_view", idx=0))


@app.route("/task1/<int:idx>")
def task1_view(idx: int):
    if not annotator_name():
        return redirect(url_for("index"))

    total = attrs_count()
    if total == 0:
        return render_template("error.html", msg="Attrs index not built yet. Run build_index.py first.")

    idx = max(0, min(idx, total - 1))
    record = fetch_attrs_record(idx)
    if not record:
        return render_template("error.html", msg=f"Could not fetch attrs record {idx}.")

    user_id = record.get("user_id", "")
    merged_attrs = record.get("merged_attributes", [])
    # Strip embeddings for display
    for a in merged_attrs:
        a.pop("embedding", None)

    # Conversations are embedded in the task1 item
    conv_records = record.get("conversations", [])
    # Flatten all conversations into a single indexed list for evidence lookup
    all_convs: List[List[Dict]] = []
    for cr in conv_records:
        turns = cr.get("conversation") or []
        if turns:
            all_convs.append(turns)

    # Build chat HTML per conversation record.
    # all_conv_idx counts only non-empty conversations, matching the indexing
    # used by extract_convs() in generate_attr_evidence.py (and thus the cache).
    total_panels = len(conv_records)
    conv_htmls = []
    all_conv_idx = 0
    for cr in conv_records:
        conv = cr.get("conversation")
        if conv:
            ch = build_chat_html(conv, c_idx_start=all_conv_idx, total_panels=total_panels)
            all_conv_idx += 1
        else:
            ch = '<div class="chat-empty">No conversation data.</div>'
        model_raw = cr.get("model", "")
        if isinstance(model_raw, list):
            model_display = ", ".join(dict.fromkeys(m for m in model_raw if m))
        else:
            model_display = model_raw or ""
        conv_htmls.append({
            "conversation_hash": cr.get("conversation_hash", ""),
            "model": model_display,
            "timestamp": cr.get("timestamp", ""),
            "html": ch,
        })

    # Load existing annotation for this index
    existing = load_existing_annotations("1").get(str(idx))

    # ✓ Annotated only when flagged OR every attribute has been judged
    if existing and existing.get("flagged"):
        is_annotated = True
    elif existing:
        judgments = existing.get("attr_judgments", [])
        is_annotated = (
            len(judgments) == len(merged_attrs) and
            all(j.get("judgment") for j in judgments)
        )
    else:
        is_annotated = False

    # Resolve evidence pointers (conv_idx, turn_idxs) -> list of turn text snippets
    evidence_key = f"{record.get('source', 'unknown')}:{user_id}"
    cached_evidence = _attr_evidence.get(evidence_key, [])
    attr_evidence: List[List[Dict]] = []
    for i in range(len(merged_attrs)):
        ptr = cached_evidence[i] if i < len(cached_evidence) else {}
        c_idx = ptr.get("conv_idx")
        t_idxs = ptr.get("turn_idxs") or []
        turns_out = []
        if c_idx is not None and 0 <= c_idx < len(all_convs):
            conv = all_convs[c_idx]
            for t_idx in t_idxs:
                if 0 <= t_idx < len(conv):
                    turn = conv[t_idx]
                    turns_out.append({
                        "role": (turn.get("role") or "").upper(),
                        "text": (turn.get("content") or "").strip()[:600],
                        "conv_idx": c_idx,
                        "turn_idx": t_idx,
                    })
                else:
                    # turn_idx is out of range for the cached conv_idx — the LLM
                    # got the conversation number wrong. Search neighboring convs
                    # for the first one where t_idx is in range.
                    remapped = False
                    for alt_c in range(len(all_convs)):
                        if alt_c == c_idx:
                            continue
                        alt_conv = all_convs[alt_c]
                        if 0 <= t_idx < len(alt_conv):
                            turn = alt_conv[t_idx]
                            print(
                                f"[evidence remap] user={user_id} attr={i} "
                                f"conv_idx={c_idx} turn_idx={t_idx} out of range "
                                f"(conv has {len(conv)} turns) -> remapped to conv_idx={alt_c}",
                                flush=True,
                            )
                            turns_out.append({
                                "role": (turn.get("role") or "").upper(),
                                "text": (turn.get("content") or "").strip()[:600],
                                "conv_idx": alt_c,
                                "turn_idx": t_idx,
                            })
                            remapped = True
                            break
                    if not remapped:
                        print(
                            f"[evidence remap] user={user_id} attr={i} "
                            f"conv_idx={c_idx} turn_idx={t_idx} out of range "
                            f"and no alternative conv found — skipping",
                            flush=True,
                        )
        attr_evidence.append(turns_out)

    task_done = count_annotated("1", total) >= total

    # Admin overlay: per-attribute list of {annotator, judgment, note} from all annotators
    admin_annots: Optional[List[List[Dict]]] = None
    admin_agreement: Optional[List[Dict]] = None
    global_stats: Optional[Dict] = None
    if is_admin():
        all_annots = load_all_annotators("1")
        admin_annots = []
        admin_agreement = []
        for a_idx in range(len(merged_attrs)):
            per_attr = []
            for ann, recs in all_annots.items():
                rec = recs.get(str(idx))
                if rec:
                    js = rec.get("attr_judgments", [])
                    if a_idx < len(js):
                        per_attr.append({
                            "annotator": ann,
                            "judgment":  js[a_idx].get("judgment", ""),
                            "note":      js[a_idx].get("note", ""),
                        })
            admin_annots.append(per_attr)
            valid_js = [p["judgment"] for p in per_attr if p["judgment"]]
            unique_js = list(dict.fromkeys(valid_js))
            admin_agreement.append({
                "n_annotators": len(per_attr),
                "disagreement": len(unique_js) > 1,
            })
        global_stats = _build_task1_global_stats(all_annots, _task1_items)

    return render_template(
        "task1.html",
        idx=idx,
        total=total,
        user_id=user_id,
        merged_attrs=merged_attrs,
        conv_htmls=conv_htmls,
        annotator=annotator_name(),
        existing=existing,
        is_annotated=is_annotated,
        attr_evidence=attr_evidence,
        admin_annots=admin_annots,
        admin_agreement=admin_agreement,
        global_stats=global_stats,
        is_admin=is_admin(),
        annotator_mode=app.config.get("ANNOTATOR_MODE", True),
        show_option_detail=app.config.get("SHOW_OPTION_DETAIL", False),
        task_done=task_done,
    )


@app.route("/task1/<int:idx>/save", methods=["POST"])
def task1_save(idx: int):
    if not annotator_name():
        return jsonify({"ok": False, "error": "Not logged in"}), 401

    data = request.get_json(force=True)
    # data = {
    #   "attr_judgments": [{"attribute": ..., "ok": bool, "note": str}, ...],
    #   "missing_attrs": str,
    #   "overall_note": str
    # }
    record = {
        "task": "1",
        "index": idx,
        "attr_judgments": data.get("attr_judgments", []),
        "missing_attrs": data.get("missing_attrs", ""),
        "overall_note": data.get("overall_note", ""),
        "flagged": data.get("flagged", False),
    }
    save_annotation("1", record)
    total = attrs_count()
    all_done = total > 0 and count_annotated("1", total) >= total
    return jsonify({"ok": True, "all_done": all_done})


@app.route("/task1/list")
def task1_list():
    """Return JSON list of attrs records for jump navigator."""
    if not annotator_name():
        return jsonify([])
    meta = get_attrs_meta_list()
    existing = load_existing_annotations("1")
    for m in meta:
        rec = existing.get(str(m["line_index"]))
        if rec and rec.get("flagged"):
            m["annotated"] = True
        elif rec:
            judgments = rec.get("attr_judgments", [])
            m["annotated"] = bool(judgments) and all(j.get("judgment") for j in judgments)
        else:
            m["annotated"] = False
    return jsonify(meta)


# ─── Routes: Task 2 — Checklist Relevance Annotation ─────────────────────────

@app.route("/task2")
def task2_redirect():
    if not annotator_name():
        return redirect(url_for("index", next="task2"))
    return redirect(url_for("task2_view", idx=0))


@app.route("/task2/<int:idx>")
def task2_view(idx: int):
    if not annotator_name():
        return redirect(url_for("index"))

    total = checklist_count()
    if total == 0:
        return render_template("error.html", msg="Checklist index not built yet. Run build_index.py first.")

    idx = max(0, min(idx, total - 1))
    record = fetch_checklist_record(idx)
    if not record:
        return render_template("error.html", msg=f"Could not fetch checklist record {idx}.")

    user_id      = record.get("user_id", "")
    prompt_text  = record.get("prompt_text", "")
    profile_attrs = record.get("profile_attributes", [])
    items        = record.get("items", [])  # model-selected relevant attributes
    prompt_index = record.get("prompt_index", -1)

    # Strip embeddings
    for a in profile_attrs:
        a.pop("embedding", None)

    # Build lookup: attribute text -> item dict (for expected_behavior / relevance)
    items_by_attr: Dict[str, Dict] = {it.get("attribute", ""): it for it in items}

    # Sort: model-relevant attributes first, then the rest (stable within each group)
    profile_attrs = sorted(
        profile_attrs,
        key=lambda a: 0 if a.get("attribute", "") in items_by_attr else 1,
    )

    # Load existing annotation
    existing = load_existing_annotations("2").get(str(idx))

    # ✓ Annotated only when flagged OR every attribute has been rated (not 'none')
    if existing and existing.get("flagged"):
        is_annotated = True
    elif existing:
        judgments = existing.get("relevance_judgments", [])
        is_annotated = (
            len(judgments) == len(profile_attrs) and
            all(j.get("rating") not in (None, "none", "") for j in judgments)
        )
    else:
        is_annotated = False

    task_done = count_annotated("2", total) >= total

    # Expected behaviors generated by LLMs (from data/behaviors/*.jsonl).
    # items_behaviors[attribute] = {model: {"explicit": "...", "implicit": "..."}}
    items_behaviors: Dict[str, Any] = _behaviors.get(idx, {})

    # Admin overlay: per-attribute list of {annotator, rating, note} from all annotators
    admin_annots: Optional[List[List[Dict]]] = None
    if is_admin():
        all_annots = load_all_annotators("2")
        admin_annots = []
        for attr in profile_attrs:
            attr_text = attr.get("attribute", "")
            per_attr = []
            for ann, recs in all_annots.items():
                rec = recs.get(str(idx))
                if rec:
                    for j in rec.get("relevance_judgments", []):
                        if j.get("attribute") == attr_text:
                            per_attr.append({
                                "annotator": ann,
                                "rating":    j.get("rating", ""),
                                "note":      j.get("note", ""),
                            })
                            break
            admin_annots.append(per_attr)

    return render_template(
        "task2.html",
        idx=idx,
        total=total,
        user_id=user_id,
        prompt_text=prompt_text,
        prompt_index=prompt_index,
        profile_attrs=profile_attrs,
        items=items,
        items_by_attr=items_by_attr,
        items_behaviors=items_behaviors,
        admin_annots=admin_annots,
        annotator=annotator_name(),
        existing=existing,
        is_annotated=is_annotated,
        annotator_mode=app.config.get("ANNOTATOR_MODE", True),
        show_option_detail=app.config.get("SHOW_OPTION_DETAIL", False),
        task_done=task_done,
    )


@app.route("/task2/<int:idx>/save", methods=["POST"])
def task2_save(idx: int):
    if not annotator_name():
        return jsonify({"ok": False, "error": "Not logged in"}), 401

    data = request.get_json(force=True)
    # Look up user_id and prompt_index from the record so they're stored alongside annotations
    meta = fetch_checklist_record(idx) or {}
    record = {
        "task": "2",
        "index": idx,
        "user_id": meta.get("user_id", ""),
        "prompt_index": meta.get("prompt_index", -1),
        "relevance_judgments": data.get("relevance_judgments", []),
        "note": data.get("note", ""),
        "flagged": data.get("flagged", False),
    }
    save_annotation("2", record)
    total = checklist_count()
    all_done = total > 0 and count_annotated("2", total) >= total
    return jsonify({"ok": True, "all_done": all_done})


@app.route("/task2/list")
def task2_list():
    """Return JSON list of checklist records for jump navigator."""
    if not annotator_name():
        return jsonify([])
    meta = get_checklist_meta_list()
    existing = load_existing_annotations("2")
    for m in meta:
        rec = existing.get(str(m["annotation_index"]))
        if rec and rec.get("flagged"):
            m["annotated"] = True
        elif rec:
            judgments = rec.get("relevance_judgments", [])
            m["annotated"] = bool(judgments) and all(
                j.get("rating") not in (None, "none", "") for j in judgments
            )
        else:
            m["annotated"] = False
    return jsonify(meta)


# ─── Routes: Task 3 — Attribute Relevance Classification ─────────────────────

@app.route("/task3")
def task3_redirect():
    if not annotator_name():
        return redirect(url_for("index", next="task3"))
    return redirect(url_for("task3_view", idx=0))


@app.route("/task3/<int:idx>")
def task3_view(idx: int):
    if not annotator_name():
        return redirect(url_for("index"))

    total = task3_count()
    if total == 0:
        return render_template("error.html", msg="No Task-3 prompts available. Check the checklist data.")

    idx = max(0, min(idx, total - 1))
    prompt_rec   = _task3_prompts[idx]
    prompt_index = prompt_rec["prompt_index"]
    prompt_text  = prompt_rec["prompt_text"]
    # Admin sees original insertion order; annotators see deterministic shuffle
    if is_admin():
        profile_attrs = prompt_rec["attributes_orig"]
    else:
        profile_attrs = prompt_rec["attributes"]

    # Load existing annotation — records are keyed by sample_index (per-user).
    # Merge judgments across all sample records for this prompt into one view.
    all_existing = load_existing_annotations("3")
    merged_relevant: Dict[str, Any] = {}
    existing_note    = ""
    existing_flagged = False
    any_existing     = False
    for attr_entry in profile_attrs:
        rec = all_existing.get(str(attr_entry["sample_index"]))
        if rec:
            any_existing = True
            if rec.get("flagged"):
                existing_flagged = True
            if not existing_note and rec.get("note"):
                existing_note = rec["note"]
            for j in rec.get("relevance_judgments", []):
                if j.get("attribute") == attr_entry["attribute"]:
                    merged_relevant[attr_entry["attribute"]] = j.get("relevant")
                    break
    existing = {
        "relevance_judgments": [
            {"attribute": a["attribute"], "relevant": merged_relevant.get(a["attribute"])}
            for a in profile_attrs
        ],
        "note":    existing_note,
        "flagged": existing_flagged,
    } if any_existing else None

    if existing and existing.get("flagged"):
        is_annotated = True
    elif existing:
        judgments = existing.get("relevance_judgments", [])
        is_annotated = (
            len(judgments) == len(profile_attrs) and
            all(j.get("relevant") is not None for j in judgments)
        )
    else:
        is_annotated = False

    task_done = count_annotated("3", total) >= total

    # Per-attribute model votes: look up via each attribute's own sample_index
    # _relevance_task3[sample_index][attribute_text][model] = bool
    attr_model_relevance: Dict[str, Dict[str, bool]] = {
        a["attribute"]: _relevance_task3.get(a["sample_index"], {}).get(a["attribute"], {})
        for a in profile_attrs
    }

    # Admin overlay: per-attribute annotator votes + per-attribute agreement stats
    # + global agreement across all data.
    admin_annots: Optional[List[List[Dict]]] = None
    admin_agreement: Optional[List[Dict]] = None
    global_agreement: Optional[Dict] = None
    if is_admin():
        from analyze_relevance_agreement import (
            load_model_votes as _load_mv,
            load_human_votes as _load_hv,
            build_agreement_data,
            RELEVANCE_DIR as _REL_DIR,
            ANNOT_DIR as _ANN_DIR,
        )
        global_agreement = build_agreement_data(
            _load_mv(_REL_DIR),
            _load_hv(_ANN_DIR, skip_admin=False),
        )
        all_annots = load_all_annotators("3")
        admin_annots = []
        admin_agreement = []
        for attr_entry in profile_attrs:
            attr_text = attr_entry["attribute"]
            per_attr: List[Dict] = []
            for ann, recs in all_annots.items():
                rec = recs.get(str(attr_entry["sample_index"]))
                if rec:
                    for j in rec.get("relevance_judgments", []):
                        if j.get("attribute") == attr_text:
                            per_attr.append({
                                "annotator": ann,
                                "relevant":  j.get("relevant"),
                            })
                            break
            admin_annots.append(per_attr)

            model_votes  = attr_model_relevance.get(attr_text, {})
            human_votes  = [p["relevant"] for p in per_attr if p["relevant"] is not None]
            all_votes    = list(model_votes.values()) + human_votes
            n_yes        = sum(1 for v in all_votes if v)
            n_no         = len(all_votes) - n_yes
            agreement_pct = round(100 * max(n_yes, n_no) / len(all_votes)) if all_votes else None
            admin_agreement.append({
                "attr":         attr_text,
                "model_votes":  model_votes,
                "n_human_yes":  sum(1 for v in human_votes if v),
                "n_human_no":   sum(1 for v in human_votes if not v),
                "n_model_yes":  sum(1 for v in model_votes.values() if v),
                "n_model_no":   sum(1 for v in model_votes.values() if not v),
                "agreement_pct": agreement_pct,
                "disagreement": len(all_votes) > 1 and n_yes > 0 and n_no > 0,
            })

    return render_template(
        "task3.html",
        idx=idx,
        total=total,
        prompt_text=prompt_text,
        prompt_index=prompt_index,
        profile_attrs=profile_attrs,
        attr_model_relevance=attr_model_relevance,
        admin_annots=admin_annots,
        admin_agreement=admin_agreement,
        global_agreement=global_agreement,
        annotator=annotator_name(),
        existing=existing,
        is_annotated=is_annotated,
        is_admin=is_admin(),
        task_done=task_done,
    )


@app.route("/task3/<int:idx>/save", methods=["POST"])
def task3_save(idx: int):
    if not annotator_name():
        return jsonify({"ok": False, "error": "Not logged in"}), 401

    data = request.get_json(force=True)
    prompt_rec    = _task3_prompts[idx] if idx < len(_task3_prompts) else {}
    prompt_index  = prompt_rec.get("prompt_index", -1)
    profile_attrs = prompt_rec.get("attributes", [])
    flagged       = data.get("flagged", False)
    note          = data.get("note", "")

    # Build attribute-text → relevant lookup from submitted judgments
    judgments_by_attr = {
        j["attribute"]: j.get("relevant")
        for j in data.get("relevance_judgments", [])
    }

    # Group attributes by sample_index and save one record per user-prompt pair
    # (same format as the old per-user task3 / convert_task2_to_task3 output)
    sample_groups: Dict[int, Dict] = {}
    for attr_entry in profile_attrs:
        sidx = attr_entry["sample_index"]
        if sidx not in sample_groups:
            sample_groups[sidx] = {
                "user_id":   attr_entry["user_id"],
                "judgments": [],
            }
        sample_groups[sidx]["judgments"].append({
            "attribute": attr_entry["attribute"],
            "relevant":  judgments_by_attr.get(attr_entry["attribute"]),
        })

    for sidx, sg in sample_groups.items():
        save_annotation("3", {
            "task":                "3",
            "index":               sidx,
            "user_id":             sg["user_id"],
            "prompt_index":        prompt_index,
            "relevance_judgments": sg["judgments"],
            "note":                note,
            "flagged":             flagged,
        })

    total    = task3_count()
    all_done = total > 0 and count_annotated("3", total) >= total
    return jsonify({"ok": True, "all_done": all_done})


@app.route("/task3/list")
def task3_list():
    """Return JSON list of task-3 prompts for the jump navigator."""
    if not annotator_name():
        return jsonify([])
    existing = load_existing_annotations("3")
    result = []
    for i, prompt_rec in enumerate(_task3_prompts[:task3_count()]):
        attrs   = prompt_rec["attributes"]
        n_attrs = len(attrs)
        # Check by sample_index (per-user records)
        flagged = any(
            existing.get(str(a["sample_index"]), {}).get("flagged") for a in attrs
        )
        if flagged:
            annotated = True
        else:
            annotated = bool(attrs) and all(
                any(
                    j.get("attribute") == a["attribute"] and j.get("relevant") is not None
                    for j in existing.get(str(a["sample_index"]), {}).get("relevance_judgments", [])
                )
                for a in attrs
            )
        result.append({
            "annotation_index": i,
            "prompt_index":     prompt_rec["prompt_index"],
            "prompt_snippet":   prompt_rec["prompt_text"][:120],
            "n_attrs":          n_attrs,
            "annotated":        annotated,
        })
    return jsonify(result)


@app.route("/task1/complete")
def task1_complete():
    if not annotator_name():
        return redirect(url_for("index"))
    prolific_code = app.config.get("PROLIFIC_CODE_TASK1", "")
    prolific_url  = (
        f"https://app.prolific.com/submissions/complete?cc={prolific_code}"
        if prolific_code else ""
    )
    return render_template(
        "complete.html",
        prolific_url=prolific_url,
        prolific_code=prolific_code,
        annotator=annotator_name(),
    )


@app.route("/task2/complete")
def task2_complete():
    if not annotator_name():
        return redirect(url_for("index"))
    prolific_code = app.config.get("PROLIFIC_CODE_TASK2", "")
    prolific_url  = (
        f"https://app.prolific.com/submissions/complete?cc={prolific_code}"
        if prolific_code else ""
    )
    return render_template(
        "complete.html",
        prolific_url=prolific_url,
        prolific_code=prolific_code,
        annotator=annotator_name(),
    )


@app.route("/task3/complete")
def task3_complete():
    if not annotator_name():
        return redirect(url_for("index"))
    prolific_code = app.config.get("PROLIFIC_CODE_TASK3", "")
    prolific_url  = (
        f"https://app.prolific.com/submissions/complete?cc={prolific_code}"
        if prolific_code else ""
    )
    return render_template(
        "complete.html",
        prolific_url=prolific_url,
        prolific_code=prolific_code,
        annotator=annotator_name(),
    )


# ─── Routes: Task 4 — User Attribute Annotation (Round 2) ────────────────────

@app.route("/task4")
def task4_redirect():
    if not annotator_name():
        return redirect(url_for("index", next="task4"))
    return redirect(url_for("task4_view", idx=0))


@app.route("/task4/<int:idx>")
def task4_view(idx: int):
    if not annotator_name():
        return redirect(url_for("index"))

    total = attrs4_count()
    if total == 0:
        return render_template("error.html", msg="Task 4 items not found.")

    idx = max(0, min(idx, total - 1))
    global_idx = task4_global_idx(idx)
    record = fetch_attrs4_record(idx)
    if not record:
        return render_template("error.html", msg=f"Could not fetch task4 record {global_idx}.")

    user_id = record.get("user_id", "")
    merged_attrs = record.get("merged_attributes", [])
    for a in merged_attrs:
        a.pop("embedding", None)

    conv_records = record.get("conversations", [])
    all_convs: List[List[Dict]] = []
    for cr in conv_records:
        turns = cr.get("conversation") or []
        if turns:
            all_convs.append(turns)

    total_panels = len(conv_records)
    conv_htmls = []
    all_conv_idx = 0
    for cr in conv_records:
        conv = cr.get("conversation")
        if conv:
            ch = build_chat_html(conv, c_idx_start=all_conv_idx, total_panels=total_panels)
            all_conv_idx += 1
        else:
            ch = '<div class="chat-empty">No conversation data.</div>'
        model_raw = cr.get("model", "")
        if isinstance(model_raw, list):
            model_display = ", ".join(dict.fromkeys(m for m in model_raw if m))
        else:
            model_display = model_raw or ""
        conv_htmls.append({
            "conversation_hash": cr.get("conversation_hash", ""),
            "model": model_display,
            "timestamp": cr.get("timestamp", ""),
            "html": ch,
        })

    existing = load_existing_annotations("4").get(str(global_idx))

    if existing and existing.get("flagged"):
        is_annotated = True
    elif existing:
        judgments = existing.get("attr_judgments", [])
        is_annotated = (
            len(judgments) == len(merged_attrs) and
            all(j.get("judgment") for j in judgments)
        )
    else:
        is_annotated = False

    evidence_key = f"{record.get('source', 'unknown')}:{user_id}"
    cached_evidence = _attr_evidence.get(evidence_key, [])
    attr_evidence: List[List[Dict]] = []
    for i in range(len(merged_attrs)):
        ptr = cached_evidence[i] if i < len(cached_evidence) else {}
        c_idx = ptr.get("conv_idx")
        t_idxs = ptr.get("turn_idxs") or []
        turns_out = []
        if c_idx is not None and 0 <= c_idx < len(all_convs):
            conv = all_convs[c_idx]
            for t_idx in t_idxs:
                if 0 <= t_idx < len(conv):
                    turn = conv[t_idx]
                    turns_out.append({
                        "role": (turn.get("role") or "").upper(),
                        "text": (turn.get("content") or "").strip()[:600],
                        "conv_idx": c_idx,
                        "turn_idx": t_idx,
                    })
        attr_evidence.append(turns_out)

    task_done = count_annotated("4", total, TASK4_START) >= total

    admin_annots: Optional[List[List[Dict]]] = None
    admin_agreement: Optional[List[Dict]] = None
    global_stats: Optional[Dict] = None
    if is_admin():
        all_annots = load_all_annotators("4")
        admin_annots = []
        admin_agreement = []
        for a_idx in range(len(merged_attrs)):
            per_attr = []
            for ann, recs in all_annots.items():
                rec = recs.get(str(global_idx))
                if rec:
                    js = rec.get("attr_judgments", [])
                    if a_idx < len(js):
                        per_attr.append({
                            "annotator": ann,
                            "judgment":  js[a_idx].get("judgment", ""),
                            "note":      js[a_idx].get("note", ""),
                        })
            admin_annots.append(per_attr)
            valid_js = [p["judgment"] for p in per_attr if p["judgment"]]
            unique_js = list(dict.fromkeys(valid_js))
            admin_agreement.append({
                "n_annotators": len(per_attr),
                "disagreement": len(unique_js) > 1,
            })
        global_stats = _build_task1_global_stats(all_annots, _task4_items)

    return render_template(
        "task4.html",
        idx=idx,
        total=total,
        user_id=user_id,
        merged_attrs=merged_attrs,
        conv_htmls=conv_htmls,
        annotator=annotator_name(),
        existing=existing,
        is_annotated=is_annotated,
        attr_evidence=attr_evidence,
        admin_annots=admin_annots,
        admin_agreement=admin_agreement,
        global_stats=global_stats,
        is_admin=is_admin(),
        annotator_mode=app.config.get("ANNOTATOR_MODE", True),
        show_option_detail=app.config.get("SHOW_OPTION_DETAIL", False),
        task_done=task_done,
    )


@app.route("/task4/<int:idx>/save", methods=["POST"])
def task4_save(idx: int):
    if not annotator_name():
        return jsonify({"ok": False, "error": "Not logged in"}), 401

    data = request.get_json(force=True)
    record = {
        "task": "4",
        "index": task4_global_idx(idx),
        "attr_judgments": data.get("attr_judgments", []),
        "missing_attrs": data.get("missing_attrs", ""),
        "overall_note": data.get("overall_note", ""),
        "flagged": data.get("flagged", False),
    }
    save_annotation("4", record)
    total = attrs4_count()
    all_done = total > 0 and count_annotated("4", total, TASK4_START) >= total
    return jsonify({"ok": True, "all_done": all_done})


@app.route("/task4/list")
def task4_list():
    if not annotator_name():
        return jsonify([])
    meta = get_attrs4_meta_list()
    existing = load_existing_annotations("4")
    for m in meta:
        rec = existing.get(str(m["line_index"]))
        if rec and rec.get("flagged"):
            m["annotated"] = True
        elif rec:
            judgments = rec.get("attr_judgments", [])
            m["annotated"] = bool(judgments) and all(j.get("judgment") for j in judgments)
        else:
            m["annotated"] = False
    return jsonify(meta)


@app.route("/task4/complete")
def task4_complete():
    if not annotator_name():
        return redirect(url_for("index"))
    prolific_code = app.config.get("PROLIFIC_CODE_TASK4", "")
    prolific_url  = (
        f"https://app.prolific.com/submissions/complete?cc={prolific_code}"
        if prolific_code else ""
    )
    return render_template(
        "complete.html",
        prolific_url=prolific_url,
        prolific_code=prolific_code,
        annotator=annotator_name(),
    )


# ─── Routes: Task 5 — Attribute Relevance Classification (Round 2) ────────────

@app.route("/task5")
def task5_redirect():
    if not annotator_name():
        return redirect(url_for("index", next="task5"))
    return redirect(url_for("task5_view", idx=0))


@app.route("/task5/<int:idx>")
def task5_view(idx: int):
    if not annotator_name():
        return redirect(url_for("index"))

    total = task5_count()
    if total == 0:
        return render_template("error.html", msg="No Task-5 prompts available. Check the task5 data.")

    idx = max(0, min(idx, total - 1))
    prompt_rec   = _task5_prompts[idx]
    prompt_index = prompt_rec["prompt_index"]
    prompt_text  = prompt_rec["prompt_text"]
    if is_admin():
        profile_attrs = prompt_rec["attributes_orig"]
    else:
        profile_attrs = prompt_rec["attributes"]

    all_existing = load_existing_annotations("5")
    merged_relevant: Dict[str, Any] = {}
    existing_note    = ""
    existing_flagged = False
    any_existing     = False
    for attr_entry in profile_attrs:
        rec = all_existing.get(str(attr_entry["sample_index"]))
        if rec:
            any_existing = True
            if rec.get("flagged"):
                existing_flagged = True
            if not existing_note and rec.get("note"):
                existing_note = rec["note"]
            for j in rec.get("relevance_judgments", []):
                if j.get("attribute") == attr_entry["attribute"]:
                    merged_relevant[attr_entry["attribute"]] = j.get("relevant")
                    break
    existing = {
        "relevance_judgments": [
            {"attribute": a["attribute"], "relevant": merged_relevant.get(a["attribute"])}
            for a in profile_attrs
        ],
        "note":    existing_note,
        "flagged": existing_flagged,
    } if any_existing else None

    if existing and existing.get("flagged"):
        is_annotated = True
    elif existing:
        judgments = existing.get("relevance_judgments", [])
        is_annotated = (
            len(judgments) == len(profile_attrs) and
            all(j.get("relevant") is not None for j in judgments)
        )
    else:
        is_annotated = False

    task_done = count_annotated("5", total) >= total

    attr_model_relevance: Dict[str, Dict[str, bool]] = {
        a["attribute"]: _relevance_task5.get(a["sample_index"], {}).get(a["attribute"], {})
        for a in profile_attrs
    }

    admin_annots: Optional[List[List[Dict]]] = None
    admin_agreement: Optional[List[Dict]] = None
    global_agreement: Optional[Dict] = None
    if is_admin():
        from analyze_relevance_agreement import (
            load_model_votes as _load_mv,
            load_human_votes as _load_hv,
            build_agreement_data,
            RELEVANCE_DIR_TASK5 as _REL_DIR_T5,
            ANNOT_DIR as _ANN_DIR,
        )
        global_agreement = build_agreement_data(
            _load_mv(_REL_DIR_T5),
            _load_hv(_ANN_DIR, skip_admin=False, task="5"),
        )
        all_annots = load_all_annotators("5")
        admin_annots = []
        admin_agreement = []
        for attr_entry in profile_attrs:
            attr_text = attr_entry["attribute"]
            per_attr: List[Dict] = []
            for ann, recs in all_annots.items():
                rec = recs.get(str(attr_entry["sample_index"]))
                if rec:
                    for j in rec.get("relevance_judgments", []):
                        if j.get("attribute") == attr_text:
                            per_attr.append({
                                "annotator": ann,
                                "relevant":  j.get("relevant"),
                            })
                            break
            admin_annots.append(per_attr)

            model_votes  = attr_model_relevance.get(attr_text, {})
            human_votes  = [p["relevant"] for p in per_attr if p["relevant"] is not None]
            all_votes    = list(model_votes.values()) + human_votes
            n_yes        = sum(1 for v in all_votes if v)
            n_no         = len(all_votes) - n_yes
            agreement_pct = round(100 * max(n_yes, n_no) / len(all_votes)) if all_votes else None
            admin_agreement.append({
                "attr":         attr_text,
                "model_votes":  model_votes,
                "n_human_yes":  sum(1 for v in human_votes if v),
                "n_human_no":   sum(1 for v in human_votes if not v),
                "n_model_yes":  sum(1 for v in model_votes.values() if v),
                "n_model_no":   sum(1 for v in model_votes.values() if not v),
                "agreement_pct": agreement_pct,
                "disagreement": len(all_votes) > 1 and n_yes > 0 and n_no > 0,
            })

    return render_template(
        "task5.html",
        idx=idx,
        total=total,
        prompt_text=prompt_text,
        prompt_index=prompt_index,
        profile_attrs=profile_attrs,
        attr_model_relevance=attr_model_relevance,
        admin_annots=admin_annots,
        admin_agreement=admin_agreement,
        global_agreement=global_agreement,
        annotator=annotator_name(),
        existing=existing,
        is_annotated=is_annotated,
        is_admin=is_admin(),
        task_done=task_done,
    )


@app.route("/task5/<int:idx>/save", methods=["POST"])
def task5_save(idx: int):
    if not annotator_name():
        return jsonify({"ok": False, "error": "Not logged in"}), 401

    data = request.get_json(force=True)
    prompt_rec    = _task5_prompts[idx] if idx < len(_task5_prompts) else {}
    prompt_index  = prompt_rec.get("prompt_index", -1)
    profile_attrs = prompt_rec.get("attributes", [])
    flagged       = data.get("flagged", False)
    note          = data.get("note", "")

    judgments_by_attr = {
        j["attribute"]: j.get("relevant")
        for j in data.get("relevance_judgments", [])
    }

    sample_groups: Dict[int, Dict] = {}
    for attr_entry in profile_attrs:
        sidx = attr_entry["sample_index"]
        if sidx not in sample_groups:
            sample_groups[sidx] = {
                "user_id":   attr_entry["user_id"],
                "judgments": [],
            }
        sample_groups[sidx]["judgments"].append({
            "attribute": attr_entry["attribute"],
            "relevant":  judgments_by_attr.get(attr_entry["attribute"]),
        })

    for sidx, sg in sample_groups.items():
        save_annotation("5", {
            "task":                "5",
            "index":               sidx,
            "user_id":             sg["user_id"],
            "prompt_index":        prompt_index,
            "relevance_judgments": sg["judgments"],
            "note":                note,
            "flagged":             flagged,
        })

    total    = task5_count()
    all_done = total > 0 and count_annotated("5", total) >= total
    return jsonify({"ok": True, "all_done": all_done})


@app.route("/task5/list")
def task5_list():
    if not annotator_name():
        return jsonify([])
    existing = load_existing_annotations("5")
    result = []
    for i, prompt_rec in enumerate(_task5_prompts[:task5_count()]):
        attrs   = prompt_rec["attributes"]
        flagged = any(
            existing.get(str(a["sample_index"]), {}).get("flagged") for a in attrs
        )
        if flagged:
            annotated = True
        else:
            annotated = bool(attrs) and all(
                any(
                    j.get("attribute") == a["attribute"] and j.get("relevant") is not None
                    for j in existing.get(str(a["sample_index"]), {}).get("relevance_judgments", [])
                )
                for a in attrs
            )
        result.append({
            "annotation_index": i,
            "prompt_index":     prompt_rec["prompt_index"],
            "prompt_snippet":   prompt_rec["prompt_text"][:120],
            "n_attrs":          len(attrs),
            "annotated":        annotated,
        })
    return jsonify(result)


@app.route("/task5/complete")
def task5_complete():
    if not annotator_name():
        return redirect(url_for("index"))
    prolific_code = app.config.get("PROLIFIC_CODE_TASK5", "")
    prolific_url  = (
        f"https://app.prolific.com/submissions/complete?cc={prolific_code}"
        if prolific_code else ""
    )
    return render_template(
        "complete.html",
        prolific_url=prolific_url,
        prolific_code=prolific_code,
        annotator=annotator_name(),
    )


# ─── Routes: Task 6 — Personalization Quality Annotation ─────────────────────

@app.route("/task6")
def task6_redirect():
    if not annotator_name():
        return redirect(url_for("index", next="task6"))
    return redirect(url_for("task6_view", idx=0))


@app.route("/task6/<int:idx>")
def task6_view(idx: int):
    if not annotator_name():
        return redirect(url_for("index"))

    total = task6_count()
    if total == 0:
        return render_template("error.html", msg="No Task-6 items available. Run run_generate_task6.sh first.")

    idx = max(0, min(idx, total - 1))
    item = _task6_items[idx]

    existing = load_existing_annotations("6").get(str(idx))
    existing_judgments: Dict[str, Optional[bool]] = {}
    existing_note    = ""
    existing_flagged = False
    if existing:
        existing_flagged = existing.get("flagged", False)
        existing_note    = existing.get("note", "")
        for j in existing.get("personalization_judgments", []):
            existing_judgments[j["attribute"]] = j.get("better")

    checklist_items = item.get("items", [])
    is_annotated = False
    if existing_flagged:
        is_annotated = True
    elif existing and checklist_items:
        is_annotated = (
            len(existing.get("personalization_judgments", [])) == len(checklist_items) and
            all(j.get("better") is not None
                for j in existing.get("personalization_judgments", []))
        )

    task_done = count_annotated("6", total) >= total

    admin_annots: Optional[List[Dict]] = None
    if is_admin():
        all_annots = load_all_annotators("6")
        admin_annots = []
        for it in checklist_items:
            attr_text = it["attribute"]
            per_attr: List[Dict] = []
            for ann, recs in all_annots.items():
                rec = recs.get(str(idx))
                if rec:
                    for j in rec.get("personalization_judgments", []):
                        if j.get("attribute") == attr_text:
                            per_attr.append({
                                "annotator": ann,
                                "better":    j.get("better"),
                            })
                            break
            admin_annots.append(per_attr)

    return render_template(
        "task6.html",
        idx=idx,
        total=total,
        item=item,
        checklist_items=checklist_items,
        existing_judgments=existing_judgments,
        existing_note=existing_note,
        existing_flagged=existing_flagged,
        is_annotated=is_annotated,
        is_admin=is_admin(),
        admin_annots=admin_annots,
        task_done=task_done,
        annotator=annotator_name(),
    )


@app.route("/task6/<int:idx>/save", methods=["POST"])
def task6_save(idx: int):
    if not annotator_name():
        return jsonify({"ok": False, "error": "Not logged in"}), 401

    total = task6_count()
    if idx >= total:
        return jsonify({"ok": False, "error": "Index out of range"}), 400

    item    = _task6_items[idx]
    data    = request.get_json(force=True)
    flagged = data.get("flagged", False)
    note    = data.get("note", "")

    judgments_by_attr: Dict[str, Optional[bool]] = {
        j["attribute"]: j.get("better")
        for j in data.get("personalization_judgments", [])
    }

    personalization_judgments = [
        {"attribute": it["attribute"], "better": judgments_by_attr.get(it["attribute"])}
        for it in item.get("items", [])
    ]

    save_annotation("6", {
        "task":                     "6",
        "index":                    idx,
        "item_index":               item.get("item_index", idx),
        "prompt_index":             item.get("prompt_index", -1),
        "user_id":                  item.get("user_id", ""),
        "personalization_judgments": personalization_judgments,
        "note":                     note,
        "flagged":                  flagged,
    })

    all_done = total > 0 and count_annotated("6", total) >= total
    return jsonify({"ok": True, "all_done": all_done})


@app.route("/task6/list")
def task6_list():
    if not annotator_name():
        return jsonify([])
    existing = load_existing_annotations("6")
    result = []
    total = task6_count()
    for i, item in enumerate(_task6_items[:total]):
        rec = existing.get(str(i))
        flagged = bool(rec and rec.get("flagged"))
        if flagged:
            annotated = True
        elif rec:
            n_attrs = len(item.get("items", []))
            judgments = rec.get("personalization_judgments", [])
            annotated = (
                n_attrs > 0 and
                len(judgments) == n_attrs and
                all(j.get("better") is not None for j in judgments)
            )
        else:
            annotated = False
        result.append({
            "annotation_index": i,
            "prompt_index":     item.get("prompt_index", -1),
            "prompt_snippet":   item.get("prompt_text", "")[:120],
            "n_attrs":          len(item.get("items", [])),
            "annotated":        annotated,
        })
    return jsonify(result)


@app.route("/task6/complete")
def task6_complete():
    if not annotator_name():
        return redirect(url_for("index"))
    prolific_code = app.config.get("PROLIFIC_CODE_TASK6", "")
    prolific_url  = (
        f"https://app.prolific.com/submissions/complete?cc={prolific_code}"
        if prolific_code else ""
    )
    return render_template(
        "complete.html",
        prolific_url=prolific_url,
        prolific_code=prolific_code,
        annotator=annotator_name(),
    )


# ─── Error template route ─────────────────────────────────────────────────────

@app.route("/status")
def status():
    return jsonify({
        "task1_items":     len(_task1_items),
        "task2_items":     len(_task2_items),
        "attrs_count":     attrs_count(),
        "checklist_count": checklist_count(),
    })


# ─── Main ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=5050)
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--debug", action="store_true")
    parser.add_argument(
        "--mode",
        choices=["annotator", "debugger"],
        default="annotator",
        help="annotator: hides model internals. debugger: shows everything.",
    )
    parser.add_argument(
        "--show-option-detail",
        action="store_true",
        default=False,
        help="Show full definitions of rating options inline next to each button.",
    )
    parser.add_argument(
        "--task1-max-users",
        type=int,
        default=10,
        help="Max number of users shown in Task 1 (default: 100).",
    )
    parser.add_argument(
        "--task2-max-items",
        type=int,
        default=0,
        help="Max number of pairs shown in Task 2 (0 = no limit).",
    )
    parser.add_argument(
        "--prolific-code-task1",
        default="C8LTQ4U9",
        help="Prolific completion code for Task 1.",
    )
    parser.add_argument(
        "--prolific-code-task2",
        default="",
        help="Prolific completion code for Task 2.",
    )
    parser.add_argument(
        "--task3-max-prompts",
        type=int,
        default=5,
        help="Max number of prompts shown in Task 3 (default: 5).",
    )
    parser.add_argument(
        "--prolific-code-task3",
        default="C1RIAWIP",
        help="Prolific completion code for Task 3.",
    )
    parser.add_argument(
        "--task4-start",
        type=int,
        default=0,
        help="First user index (inclusive) shown in Task 4 (default: 0).",
    )
    parser.add_argument(
        "--task4-end",
        type=int,
        default=40,
        help="Last user index (exclusive) shown in Task 4 (0 = no limit).",
    )
    parser.add_argument(
        "--prolific-code-task4",
        default="C8LTQ4U9",
        help="Prolific completion code for Task 4.",
    )
    parser.add_argument(
        "--task5-max-prompts",
        type=int,
        default=100,
        help="Max number of prompts shown in Task 5 (default: 100).",
    )
    parser.add_argument(
        "--prolific-code-task5",
        default="C1RIAWIP",
        help="Prolific completion code for Task 5.",
    )
    parser.add_argument(
        "--task6-max-items",
        type=int,
        default=0,
        help="Max number of items shown in Task 6 (0 = no limit).",
    )
    parser.add_argument(
        "--prolific-code-task6",
        default="",
        help="Prolific completion code for Task 6.",
    )
    args = parser.parse_args()

    # Apply workload limits (override module-level defaults)
    TASK1_MAX_USERS = args.task1_max_users
    TASK2_MAX_ITEMS = args.task2_max_items
    TASK3_MAX_PROMPTS = args.task3_max_prompts
    TASK4_START = args.task4_start
    TASK4_END = args.task4_end
    TASK5_MAX_PROMPTS = args.task5_max_prompts
    TASK6_MAX_ITEMS = args.task6_max_items

    app.config["ANNOTATOR_MODE"] = (args.mode == "annotator")
    app.config["SHOW_OPTION_DETAIL"] = args.show_option_detail
    app.config["PROLIFIC_CODE_TASK1"] = args.prolific_code_task1
    app.config["PROLIFIC_CODE_TASK2"] = args.prolific_code_task2
    app.config["PROLIFIC_CODE_TASK3"] = args.prolific_code_task3
    app.config["PROLIFIC_CODE_TASK4"] = args.prolific_code_task4
    app.config["PROLIFIC_CODE_TASK5"] = args.prolific_code_task5
    app.config["PROLIFIC_CODE_TASK6"] = args.prolific_code_task6
    app.run(host=args.host, port=args.port, debug=args.debug)
